#!/usr/bin/env python3
"""net_throughput_test.py -- 5-channel x 100 Hz full-fit network soak for EHome nodes.

Goal
----
Prove that the network configuration in esp32-collector/sdkconfig.defaults can
carry the full fit (S3: 5 channels x 100 Hz = 500 DataReports/s, ~300 B each =
~150 KB/s raw payload) with:
  * drop rate  < 0.1 %
  * MQTT stays connected (no disconnect / reconnect)
  * end-to-end latency p99 < 200 ms

How it works
------------
1. Connects to the MQTT broker as the *server side* (the same thing the Go
   backend does) and subscribes to ``nodes/<node>/up`` and
   ``nodes/<node>/down``.
2. Publishes a ConfigManifest (5 channels, interval_ms=10) to
   ``nodes/<node>/down``, which the firmware applies transactionally.  Each
   channel is a real hardware channel with DMA disabled and a tiny UART
   read size, so the scheduler performs real bus transactions.  The point of
   the manifest is to drive the firmware's *scheduler* at 100 Hz; the wire
   payload is generated by the node's own DataReports.
3. For the configured soak window it counts DataReports per channel, watches
   for sequence gaps (drop rate), and measures MQTT receive-time latency using
   the node's own ``timestamp_us`` field (esp_timer_get_time, monotonic, not
   wall clock).  Clock offset is removed by using the *minimum* observed
   received-minus-timestamp difference as the reference.

   Latency convention (read before quoting a number): the reported p99 is the
   *additional* one-way delay above the best observed case (jitter + queueing),
   NOT the absolute device->host propagation time -- min(recv - ts) absorbs any
   constant offset, and host and device have no shared time base without NTP.
   That is the right gate for a 100 Hz control loop (is queueing/jitter under
   control?), but do not report it as end-to-end propagation latency.
4. Reports pass/fail against the three acceptance criteria.

Usage
-----
  python3 tools/net_throughput_test.py \
      --broker 192.168.20.6 --port 1883 --node 1001 \
      --duration 60 [--channels 5] [--hz 100] [--json out.json]

Defaults assume the firmware's CONFIG_COLLECTOR_NODE_ID and that the host can
reach the MQTT broker (e.g. the production EMQX at 192.168.20.6:1883).

Wire format
-----------
protobuf-style TLV, first byte = message type.  Encoded here exactly as
backend/internal/nodemgr/sender_snapshot.go encodes ConfigManifest:
  manifest: field 1 = manifest_id (str), field 8 = sync_id (str),
            field 3 = template (sub), field 4 = channel (sub)
  template: field 1 = id, field 2 = write_data, field 3 = read_length,
            field 4 = delay_ms
  channel:  field 1 = id, field 2 = hardware_id, field 3 = template_ids
            (repeated varint), field 4 = interval_ms, field 5 = enabled,
            field 6 = bus_type (1=UART), field 7 = bus_config
  DataReport: field 1 = channel_id, field 2 = timestamp_us, field 3 = sequence,
            field 4 = raw payload, field 5 = error_code

Requires: paho-mqtt >= 2.0 (``python3 -m pip install paho-mqtt``).
Note: on this host paho is available in the IDF 6.0 python env
(/home/sun/.espressif/python_env/idf6.0_py3.14_env/bin/python) or install it
into any python3.
"""

from __future__ import annotations

import argparse
import json
import math
import statistics
import struct
import sys
import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional

try:
    import paho.mqtt.client as mqtt
except ImportError:
    sys.stderr.write(
        "paho-mqtt is required: python3 -m pip install paho-mqtt\n"
        "On the dev host it is already present in "
        "/home/sun/.espressif/python_env/idf6.0_py3.14_env/bin/python\n")
    raise SystemExit(2)

MSG_HELLO = 0x01
MSG_STATUS_RPT = 0x02
MSG_DATA_RPT = 0x03
MSG_CONFIG_MFST = 0x04
MSG_CONFIG_RSLT = 0x05
MSG_PONG = 0x09
MSG_HELLO_ACK = 0x12


# --------------------------------------------------------------------------
# protobuf-wire TLV helpers (mirror components/frame/frame_codec.c)
# --------------------------------------------------------------------------
def enc_varint(value: int) -> bytes:
    out = bytearray()
    while value > 0x7F:
        out.append((value & 0x7F) | 0x80)
        value >>= 7
    out.append(value & 0x7F)
    return bytes(out)


def field_varint(num: int, value: int) -> bytes:
    return enc_varint((num << 3) | 0) + enc_varint(value)


def field_bytes(num: int, data: bytes) -> bytes:
    return enc_varint((num << 3) | 2) + enc_varint(len(data)) + data


def dec_varint(buf: bytes, pos: int):
    value = 0
    shift = 0
    while True:
        if pos >= len(buf):
            raise ValueError("truncated varint")
        b = buf[pos]
        pos += 1
        value |= (b & 0x7F) << shift
        if not (b & 0x80):
            return value, pos
        shift += 7


def decode_fields(payload: bytes):
    """Yield (field_num, wire_type, value) for a frame body (no msg type)."""
    pos = 0
    while pos < len(payload):
        tag, pos = dec_varint(payload, pos)
        fnum, wire = tag >> 3, tag & 7
        if wire == 0:
            val, pos = dec_varint(payload, pos)
        elif wire == 2:
            ln, pos = dec_varint(payload, pos)
            val = payload[pos:pos + ln]
            pos += ln
        elif wire == 5:
            val = struct.unpack_from("<I", payload, pos)[0]
            pos += 4
        elif wire == 1:
            val = struct.unpack_from("<Q", payload, pos)[0]
            pos += 8
        else:
            raise ValueError(f"unsupported wire type {wire}")
        yield fnum, wire, val


# --------------------------------------------------------------------------
# Manifest construction
# --------------------------------------------------------------------------
# Full-fit channel plan per target.  A "5-channel S3 full fit" in this repo
# means the physical maximum: 3 HP UART + 1 SPI + 1 I2C (hw_tables.c:111-136).
# A manifest must reference *distinct, real* controllers, otherwise
# bus_manager's preflight (`validate_manifest_resources`) rejects the whole
# frame before any channel is applied.  Pin values below are the hw_tables.c
# defaults for each controller; bus_config layouts are the ones bus_dma parses:
#   UART: [tx, rx, baud_be32]          (bus_dma.c:377-379, len>=6)
#   SPI:  [cs, mode, freq_be32, mosi, miso, sclk] (bus_dma.c:987-1000, len>=9)
#   I2C:  [sda, scl, addr, freq_be32]  (bus_dma.c:1338-1341, len>=7)
S3_FULL_FIT = [
    # (bus_type, tx/cs/sda, rx/mode/scl, baud/freq, extra)
    {"bus_type": 1, "pins": (43, 44, 115200)},                    # UART0 (console port)
    {"bus_type": 1, "pins": (4, 5, 115200)},                      # UART1
    {"bus_type": 1, "pins": (1, 2, 115200)},                      # UART2
    {"bus_type": 3, "pins": (10, 0, 1_000_000, 11, 13, 12)},      # SPI2
    {"bus_type": 2, "pins": (8, 9, 0x48, 400_000)},               # I2C0 addr 0x48
]

C6_FULL_FIT = [
    {"bus_type": 1, "pins": (16, 17, 115200)},                    # UART0
    {"bus_type": 1, "pins": (20, 21, 115200)},                    # UART1
    {"bus_type": 3, "pins": (5, 0, 1_000_000, 23, 19, 18)},       # SPI2
    {"bus_type": 2, "pins": (21, 22, 0x48, 400_000)},             # I2C0
]


def encode_bus_config(spec) -> bytes:
    bt = spec["bus_type"]
    p = spec["pins"]
    if bt == 1:   # UART: tx, rx, baud_be32
        tx, rx, baud = p
        return bytes([tx & 0xFF, rx & 0xFF]) + baud.to_bytes(4, "big")
    if bt == 3:   # SPI: cs, mode, freq_be32, mosi, miso, sclk
        cs, mode, freq, mosi, miso, sclk = p
        return (bytes([cs & 0xFF, mode & 0xFF]) + freq.to_bytes(4, "big")
                + bytes([mosi & 0xFF, miso & 0xFF, sclk & 0xFF]))
    if bt == 2:   # I2C: sda, scl, addr, freq_be32
        sda, scl, addr, freq = p
        return bytes([sda & 0xFF, scl & 0xFF, addr & 0xFF]) + freq.to_bytes(4, "big")
    raise ValueError(f"unknown bus_type {bt}")


def build_manifest(manifest_id: str, sync_id: str, plan: List[dict],
                   interval_ms: int, write_data: bytes = b"\x01",
                   read_length: int = 300) -> bytes:
    frame = bytearray([MSG_CONFIG_MFST])
    frame += field_bytes(1, manifest_id.encode())
    frame += field_bytes(8, sync_id.encode())

    # One tiny template reused by all channels: write 1 byte, read 1 byte.
    tmpl = bytearray()
    tmpl += field_varint(1, 1)                 # template id
    tmpl += field_bytes(2, write_data)         # write_data
    tmpl += field_varint(3, read_length)       # read_length
    tmpl += field_varint(4, 2)                 # delay_ms (2 ms)
    frame += field_bytes(3, bytes(tmpl))

    for idx, spec in enumerate(plan):
        ch = bytearray()
        ch += field_varint(1, idx + 1)          # id
        ch += field_varint(2, 1)                # hardware_id
        ch += field_bytes(3, enc_varint(1))     # template_ids = [1]
        ch += field_varint(4, interval_ms)      # interval_ms
        ch += field_varint(5, 1)                # enabled
        ch += field_varint(6, spec["bus_type"]) # bus_type
        ch += field_bytes(7, encode_bus_config(spec))  # bus_config
        # dma_enabled omitted on purpose: default path disables DMA for these
        # tiny transfers, keeping the test independent of DMA availability.
        frame += field_bytes(4, bytes(ch))
    return bytes(frame)


# --------------------------------------------------------------------------
# Observation
# --------------------------------------------------------------------------
@dataclass
class ChannelStats:
    channel_id: int = 0
    first_ts: int = 0
    last_ts: int = 0
    last_seq: int = 0
    count: int = 0
    max_seq_gap: int = 1
    seq_gaps: int = 0
    missing: int = 0
    latencies_ms: List[float] = field(default_factory=list)

    def observe(self, timestamp_us: int, sequence: int, received_us: int) -> None:
        prev = self.last_seq if self.count else None
        self.count += 1
        if prev is not None:
            gap = (sequence - prev) & 0xFFFFFFFF
            if gap > 1:
                # A gap can be a reordering (rare, QoS0/QoS1 over TCP = in order,
                # so treat >1 as loss/reorder and count the missing reports).
                self.seq_gaps += 1
                self.missing += gap - 1
                self.max_seq_gap = max(self.max_seq_gap, gap)
        self.last_seq = sequence
        self.last_ts = timestamp_us
        if self.first_ts == 0:
            self.first_ts = timestamp_us
        self.latencies_ms.append(0.0)  # placeholder; refined after clock offset


def percentile(values: List[float], pct: float) -> float:
    if not values:
        return float("nan")
    ordered = sorted(values)
    rank = (pct / 100.0) * (len(ordered) - 1)
    lo = int(math.floor(rank))
    hi = int(math.ceil(rank))
    if lo == hi:
        return ordered[lo]
    return ordered[lo] + (ordered[hi] - ordered[lo]) * (rank - lo)


class Harness:
    def __init__(self, args):
        self.args = args
        self.connected = False
        self.connected_at: Optional[float] = None
        self.disconnects = 0
        self.total_msgs = 0
        self.data_msgs = 0
        self.other_msgs = 0
        self.config_results: List[dict] = []
        self.pongs = 0
        self.channels: Dict[int, ChannelStats] = {}
        self.samples = []  # (recv_us, timestamp_us, channel_id, raw_len)
        self.total_raw_bytes = 0
        self.t0 = 0.0
        self.errors: List[str] = []
        self.status_seen = 0
        self.stopping = False

    def on_connect(self, client, userdata, flags, reason_code, properties=None):
        # paho-mqtt v2 passes a ReasonCode object (not an int); compare its value.
        rc = getattr(reason_code, "value", reason_code)
        if rc != 0:
            self.errors.append(f"connect rc={reason_code}")
            return
        self.connected = True
        self.connected_at = time.time()
        client.subscribe(f"nodes/{self.args.node}/up", qos=0)
        client.subscribe(f"nodes/{self.args.node}/down", qos=0)
        print(f"[harness] connected to {self.args.broker}:{self.args.port}, "
              f"subscribed nodes/{self.args.node}/up|down")

    def on_disconnect(self, *cb_args):
        # paho-mqtt v2 may pass (client, userdata, disconnect_flags, reason_code,
        # properties) while v1 passes (client, userdata, rc).  Accept both.
        reason_code = cb_args[-2] if len(cb_args) >= 5 else (
            cb_args[2] if len(cb_args) >= 3 else None)
        # paho calls this on the initial failed connect too; only count after login.
        # The harness' own client.disconnect() at the end is intentional.
        if self.connected and not self.stopping:
            self.disconnects += 1
            print(f"[harness] !! MQTT disconnected: rc={reason_code}")

    def on_message(self, client, userdata, msg):
        self.total_msgs += 1
        payload = msg.payload
        if not payload:
            return
        mtype = payload[0]
        body = payload[1:]
        if mtype == MSG_DATA_RPT:
            self.data_msgs += 1
            try:
                self._on_data_report(body)
            except Exception as exc:  # never let parsing kill the soak
                self.errors.append(f"data report parse: {exc}")
        elif mtype == MSG_CONFIG_RSLT:
            try:
                self._on_config_result(body)
            except Exception as exc:
                self.errors.append(f"config result parse: {exc}")
        elif mtype == MSG_PONG:
            self.pongs += 1
        elif mtype == MSG_STATUS_RPT:
            self.status_seen += 1
        else:
            self.other_msgs += 1

    def _on_data_report(self, body: bytes):
        ch = ts = seq = 0
        raw = b""
        for fnum, wire, val in decode_fields(body):
            if fnum == 1:
                ch = val
            elif fnum == 2:
                ts = val
            elif fnum == 3:
                seq = val
            elif fnum == 4:
                raw = val
        if ch == 0:
            return
        recv_us = time.perf_counter() * 1e6
        st = self.channels.setdefault(ch, ChannelStats(channel_id=ch))
        st.observe(ts, seq, recv_us)
        # store raw sample for offset-relative latency computation
        self.total_raw_bytes += len(raw)
        self.samples.append((recv_us, ts, ch, len(raw)))

    def _on_config_result(self, body: bytes):
        rec: dict = {}
        for fnum, wire, val in decode_fields(body):
            if fnum == 1 and wire == 2:
                rec["manifest_id"] = bytes(val).decode(errors="replace")
            elif fnum == 2 and wire == 2:
                rec["sync_id"] = bytes(val).decode(errors="replace")
            elif fnum == 3:
                rec["success"] = bool(val)
            elif fnum == 4:
                rec["error_code"] = val
            elif fnum == 5 and wire == 2:
                rec["error_msg"] = bytes(val).decode(errors="replace")
        self.config_results.append(rec)
        print(f"[harness] ConfigResult: {rec}")

    # ------------------------------------------------------------------
    def run(self, manifest: bytes) -> dict:
        args = self.args
        client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2,
                             client_id=f"net-throughput-{int(time.time())}")
        client.on_connect = self.on_connect
        client.on_disconnect = self.on_disconnect
        client.on_message = self.on_message
        try:
            client.connect(args.broker, args.port, keepalive=30)
        except Exception as exc:
            raise SystemExit(f"cannot reach broker {args.broker}:{args.port}: {exc}")
        client.loop_start()

        deadline = time.time() + 10
        while not self.connected and time.time() < deadline:
            time.sleep(0.1)
        if not self.connected:
            raise SystemExit("MQTT connect timed out")

        # Wait for the node's first Hello traffic so we know it is alive.
        print("[harness] waiting for node up-traffic (Hello/Status)...")
        hello_deadline = time.time() + args.hello_timeout
        while time.time() < hello_deadline and self.other_msgs == 0 and self.status_seen == 0:
            time.sleep(0.2)
        if self.status_seen == 0 and self.other_msgs == 0:
            print("[harness] WARNING: no Hello/Status seen; is the node powered and "
                  "connected to the same broker?")

        print(f"[harness] publishing manifest: {args.channels} ch x {args.hz} Hz "
              f"(interval_ms={manifest_interval_ms(args.hz)})")
        client.publish(f"nodes/{args.node}/down", manifest, qos=0)

        # Wait for ConfigResult success so the soak measures an applied config.
        cr_deadline = time.time() + args.config_timeout
        ok = False
        while time.time() < cr_deadline:
            if self.config_results:
                ok = any(r.get("success") for r in self.config_results)
                break
            time.sleep(0.2)
        if not ok:
            print("[harness] WARNING: no successful ConfigResult observed "
                  f"(results={self.config_results}); continuing soak anyway")

        print(f"[harness] soak for {args.duration}s ...")
        self.t0 = time.time()
        self.soak_start_samples = len(self.samples)
        try:
            while time.time() - self.t0 < args.duration:
                time.sleep(1.0)
                if args.progress:
                    self._progress()
        finally:
            self.stopping = True
            client.disconnect()
            client.loop_stop()
        return self._report()

    def _progress(self):
        elapsed = time.time() - self.t0
        n = len(self.samples)
        rate = n / elapsed if elapsed > 0 else 0
        print(f"[harness] t={elapsed:5.1f}s reports={n} ({rate:6.1f}/s) "
              f"connected={self.connected} disconnects={self.disconnects}")

    def _report(self) -> dict:
        args = self.args
        elapsed = max(time.time() - self.t0, 1e-9)
        total = len(self.samples)
        expected = args.channels * args.hz * elapsed
        dropped = sum(st.missing for st in self.channels.values())
        drop_rate = dropped / expected if expected > 0 else float("nan")

        # Latency: remove constant clock offset using the minimum difference.
        # recv_us is host perf_counter us, ts is device esp_timer us; both are
        # monotonic but unrelated.  min(recv - ts) is the best estimate of the
        # offset; the residual is one-way latency (device -> broker -> host).
        deltas = [(r - ts) for (r, ts, _, _) in self.samples]
        offset = min(deltas) if deltas else 0.0
        lat = [(d - offset) / 1000.0 for d in deltas]  # ms
        p50 = percentile(lat, 50)
        p99 = percentile(lat, 99)
        p999 = percentile(lat, 99.9)
        worst = max(lat) if lat else float("nan")

        observed_hz = {ch: (st.count / elapsed) for ch, st in self.channels.items()}

        payload_kbps = (self.total_raw_bytes / 1024.0) / elapsed
        # A drop rate only means something once reports actually arrived: 0
        # missing out of 0 received is not "0% loss", it is "no evidence".
        drop_ok = (total > 0) and (drop_rate < 0.001)
        mqtt_ok = self.disconnects == 0 and self.connected
        lat_ok = p99 < 200.0 if lat else False
        rate_ok = (total > 0) and (
            abs(total / elapsed - expected / elapsed) / (args.channels * args.hz) < 0.05)

        result = {
            "broker": f"{args.broker}:{args.port}",
            "node": args.node,
            "duration_s": round(elapsed, 2),
            "channels": args.channels,
            "target_hz": args.hz,
            "expected_reports": round(expected),
            "received_reports": total,
            "aggregate_rate_hz": round(total / elapsed, 1),
            "raw_payload_kb_s": round(payload_kbps, 1),
            "per_channel_hz": {str(k): round(v, 1) for k, v in observed_hz.items()},
            "dropped_reports": dropped,
            "drop_rate": drop_rate,
            "sequences_with_gap": sum(st.seq_gaps for st in self.channels.values()),
            "mqtt_disconnects": self.disconnects,
            "mqtt_connected_at_end": mqtt_ok,
            "latency_ms": {"p50": round(p50, 2), "p99": round(p99, 2),
                           "p99_9": round(p999, 2), "max": round(worst, 2),
                           "samples": len(lat)},
            "config_results": self.config_results,
            "status_reports": self.status_seen,
            "pongs": self.pongs,
            "parse_errors": self.errors[:10],
            "pass": {
                "drop_rate_lt_0.1pct": bool(drop_ok),
                "mqtt_no_disconnect": bool(mqtt_ok),
                "latency_p99_lt_200ms": bool(lat_ok),
                "throughput_within_5pct": bool(rate_ok),
                "payload_ge_140kb_s": bool(payload_kbps >= 140.0) if args.read_length >= 300 else True,
            },
        }
        if args.allow_no_hardware:
            result["pass"]["payload_ge_140kb_s"] = True  # informational only
            result["note"] = ("--allow-no-hardware: reports may be timeout/error "
                              "reports; this run does NOT prove the 150 KB/s "
                              "payload budget.")
        result["overall_pass"] = all(result["pass"].values())
        result["note_no_data"] = (
            "no DataReports received: the node was not connected to this broker, "
            "so loss/latency/payload numbers are NOT evidence"
            if total == 0 else "")
        return _json_safe(result)


def _json_safe(obj):
    """Replace non-finite floats so the result is valid, portable JSON."""
    if isinstance(obj, float):
        return obj if math.isfinite(obj) else None
    if isinstance(obj, dict):
        return {k: _json_safe(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_json_safe(v) for v in obj]
    return obj


def manifest_interval_ms(hz: int) -> int:
    return max(10, int(round(1000.0 / hz)))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--broker", required=True, help="MQTT broker host")
    ap.add_argument("--port", type=int, default=1883)
    ap.add_argument("--node", default="1001", help="node id (nodes/<id>/...)")
    ap.add_argument("--duration", type=float, default=60.0, help="soak seconds")
    ap.add_argument("--channels", type=int, default=5,
                    help="1..5 on S3 (3 UART+SPI+I2C), 1..4 on C6")
    ap.add_argument("--target", choices=["s3", "c6"], default="s3")
    ap.add_argument("--read-length", type=int, default=300,
                    help="bytes read per sample; 300 = the modelled DataReport payload")
    ap.add_argument("--allow-no-hardware", action="store_true",
                    help="do not require --read-length to match real field devices; "
                         "reports may be timeout/error reports and the payload-rate "
                         "check is downgraded to informational")
    ap.add_argument("--hz", type=int, default=100)
    ap.add_argument("--hello-timeout", type=float, default=20.0)
    ap.add_argument("--config-timeout", type=float, default=20.0)
    ap.add_argument("--json", help="write the result dict as JSON to this path")
    ap.add_argument("--no-progress", dest="progress", action="store_false")
    args = ap.parse_args()

    base_plan = C6_FULL_FIT if args.target == "c6" else S3_FULL_FIT
    if args.channels > len(base_plan):
        raise SystemExit(f"--channels {args.channels} > physical {args.target.upper()} "
                         f"full fit ({len(base_plan)}: 3 UART+SPI+I2C)")
    plan = base_plan[:args.channels]
    manifest = build_manifest(
        manifest_id=f"netperf-{int(time.time())}",
        sync_id=f"netperf-sync-{int(time.time())}",
        plan=plan,
        interval_ms=manifest_interval_ms(args.hz),
        read_length=args.read_length,
    )
    print(f"[harness] manifest frame {len(manifest)} B: {manifest.hex()}")

    harness = Harness(args)
    result = harness.run(manifest)

    print("\n" + "=" * 72)
    print("RESULT")
    print("=" * 72)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    if args.json:
        with open(args.json, "w", encoding="utf-8") as fh:
            json.dump(result, fh, indent=2, ensure_ascii=False)
        print(f"[harness] wrote {args.json}")

    print("\nACCEPTANCE:")
    for k, v in result["pass"].items():
        print(f"  [{'PASS' if v else 'FAIL'}] {k}")
    print(f"  OVERALL: {'PASS' if result['overall_pass'] else 'FAIL'}")
    return 0 if result["overall_pass"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
