package frame

import (
	"errors"
	"fmt"
)

// device_op_wire.go -- the payload format for MsgDeviceOp (0x22) / MsgDeviceOpAck (0x23).
//
// # Why this file exists at all
//
// The firmware defined the operation CODES (device_op.h: DEVICE_OP_REBOOT=1,
// DEVICE_OP_FACTORY_RESET_KEEP_CONN=2) but neither end ever defined the PAYLOAD
// FORMAT, and neither end had a decoder. A message type with no agreed body is
// not a protocol, so this file defines it -- in pkg/frame, which design §2.5.2
// designates as the single definition site for wire contracts, so there is one
// place to change and one place to check.
//
// # Format (tag = field<<3 | wire_type, the same encoding the rest of the protocol uses)
//
//	MsgDeviceOp (0x22), server -> device
//	  field 1  varint  op_code
//	  field 2  bytes   request_id   (correlation id, non-empty)
//
//	MsgDeviceOpAck (0x23), device -> server
//	  field 1  varint  result_code
//	  field 2  bytes   request_id   (echoed back, must match the request)
//	  field 3  bytes   detail       (optional, human-readable)
//
// # request_id is mine, and needs designer confirmation
//
// The design never specified a correlation id. I added one because without it
// the server cannot tell WHICH request an ACK answers: reboot is single-flight
// per node and the device retries ACKs, so a late ACK from an earlier attempt
// would otherwise be attributed to the current one -- reporting success for an
// operation that actually failed. Same class of decision as the big-endian
// choice (§42.3): the implementer picked, and it needs confirming before the
// firmware side is written.

// DeviceOpFieldOp / RequestID / Result / Detail are the field numbers above.
const (
	DeviceOpFieldOp        uint8 = 1
	DeviceOpFieldRequestID uint8 = 2

	DeviceOpAckFieldResult    uint8 = 1
	DeviceOpAckFieldRequestID uint8 = 2
	DeviceOpAckFieldDetail    uint8 = 3
)

// MaxDeviceOpRequestIDBytes bounds the correlation id. It is not a tuning knob:
// the id is generated by this server, and a bound keeps a buggy/hostile peer
// from making us allocate an unbounded string.
const MaxDeviceOpRequestIDBytes = 64

// MaxDeviceOpDetailBytes bounds the human-readable detail in an ACK.
const MaxDeviceOpDetailBytes = 256

// DeviceOpRequest is a decoded 0x22.
type DeviceOpRequest struct {
	Op        DeviceOp
	RequestID string
}

// EncodeDeviceOp builds the payload for a downlink MsgDeviceOp.
//
// The payload's FIRST BYTE is the message type (2.x convention, and what the
// shared vectors encode), so this returns a complete payload including it.
func EncodeDeviceOp(op DeviceOp, requestID string) ([]byte, error) {
	if requestID == "" {
		return nil, fmt.Errorf("device op requires a non-empty request_id " +
			"(without it a late ACK cannot be told apart from the current one)")
	}
	if len(requestID) > MaxDeviceOpRequestIDBytes {
		return nil, fmt.Errorf("device op request_id is %d bytes, limit %d",
			len(requestID), MaxDeviceOpRequestIDBytes)
	}
	if op != DeviceOpReboot && op != DeviceOpFactoryResetKeepConn {
		return nil, fmt.Errorf("unknown device op %d", uint8(op))
	}
	enc := NewEncoder(MsgDeviceOp)
	enc.EncodeVarint(DeviceOpFieldOp, uint64(op))
	enc.EncodeString(DeviceOpFieldRequestID, requestID)
	return enc.Bytes(), nil
}

// DecodeDeviceOp parses a 0x22 payload.
func DecodeDeviceOp(payload []byte) (DeviceOpRequest, error) {
	var out DeviceOpRequest
	dec, err := NewDecoder(payload)
	if err != nil {
		return out, fmt.Errorf("device op: %w", err)
	}
	if dec.MsgType() != MsgDeviceOp {
		return out, fmt.Errorf("device op: message type 0x%02X, want 0x%02X",
			dec.MsgType(), MsgDeviceOp)
	}
	seenOp, seenReq := false, false
	for {
		field, err := dec.NextField()
		if err != nil {
			if errors.Is(err, ErrEndOfFrame) {
				break
			}
			return out, fmt.Errorf("device op: malformed fields: %w", err)
		}
		switch field.FieldNum {
		case DeviceOpFieldOp:
			if field.WireType != WireVarint {
				return out, fmt.Errorf("device op: op wire type %d", field.WireType)
			}
			out.Op = DeviceOp(GetUint64(field))
			seenOp = true
		case DeviceOpFieldRequestID:
			if field.WireType != WireLengthDelimited {
				return out, fmt.Errorf("device op: request_id wire type %d", field.WireType)
			}
			out.RequestID = GetString(field)
			seenReq = true
		}
	}
	if !seenOp {
		return out, fmt.Errorf("device op: missing op_code")
	}
	if !seenReq || out.RequestID == "" {
		return out, fmt.Errorf("device op: missing request_id")
	}
	return out, nil
}

// DeviceOpAck is a decoded 0x23.
type DeviceOpAck struct {
	RequestID string
	Result    DeviceOpResult
	Detail    string
}

// EncodeDeviceOpAck builds a 0x23 payload (used by tests and by any non-firmware
// peer; the firmware builds this on-device).
func EncodeDeviceOpAck(requestID string, result DeviceOpResult, detail string) ([]byte, error) {
	if requestID == "" {
		return nil, fmt.Errorf("device op ack requires a non-empty request_id")
	}
	if len(detail) > MaxDeviceOpDetailBytes {
		return nil, fmt.Errorf("device op ack detail is %d bytes, limit %d",
			len(detail), MaxDeviceOpDetailBytes)
	}
	enc := NewEncoder(MsgDeviceOpAck)
	enc.EncodeVarint(DeviceOpAckFieldResult, uint64(result))
	enc.EncodeString(DeviceOpAckFieldRequestID, requestID)
	if detail != "" {
		enc.EncodeString(DeviceOpAckFieldDetail, detail)
	}
	return enc.Bytes(), nil
}

// DecodeDeviceOpAck parses a 0x23 payload.
//
// Result codes are NOT range-checked: an unrecognised code means the device is
// newer than this server, and rejecting it would turn "newer firmware" into
// "operation failed with no reason" (see DeviceOpResultName).
func DecodeDeviceOpAck(payload []byte) (DeviceOpAck, error) {
	var out DeviceOpAck
	dec, err := NewDecoder(payload)
	if err != nil {
		return out, fmt.Errorf("device op ack: %w", err)
	}
	if dec.MsgType() != MsgDeviceOpAck {
		return out, fmt.Errorf("device op ack: message type 0x%02X, want 0x%02X",
			dec.MsgType(), MsgDeviceOpAck)
	}
	seenResult, seenReq := false, false
	for {
		field, err := dec.NextField()
		if err != nil {
			if errors.Is(err, ErrEndOfFrame) {
				break
			}
			return out, fmt.Errorf("device op ack: malformed fields: %w", err)
		}
		switch field.FieldNum {
		case DeviceOpAckFieldResult:
			if field.WireType != WireVarint {
				return out, fmt.Errorf("device op ack: result wire type %d", field.WireType)
			}
			v := GetUint64(field)
			if v > 0xFF {
				return out, fmt.Errorf("device op ack: result %d overflows a byte", v)
			}
			out.Result = DeviceOpResult(v)
			seenResult = true
		case DeviceOpAckFieldRequestID:
			if field.WireType != WireLengthDelimited {
				return out, fmt.Errorf("device op ack: request_id wire type %d", field.WireType)
			}
			out.RequestID = GetString(field)
			seenReq = true
		case DeviceOpAckFieldDetail:
			if field.WireType != WireLengthDelimited {
				return out, fmt.Errorf("device op ack: detail wire type %d", field.WireType)
			}
			out.Detail = GetString(field)
		}
	}
	if !seenResult {
		return out, fmt.Errorf("device op ack: missing result_code")
	}
	if !seenReq || out.RequestID == "" {
		return out, fmt.Errorf("device op ack: missing request_id")
	}
	return out, nil
}
