/**
 * Sensor metadata maps — shared across Dashboard, EdgeDeviceDetail, etc.
 * S6 fix: Extracted from Dashboard.vue to eliminate duplication.
 */

/** 传感器中文名映射 */
export const sensorNameMap: Record<string, string> = {
  temperature: '温度',
  pressure: '气压',
  humidity: '湿度',
  wind_direction: '风向',
  wind_speed: '风速',
  light: '光照',
  noise: '噪声',
  co2: 'CO₂',
  pm25: 'PM2.5',
  rainfall: '降雨量',
  uv: '紫外线',
  illuminance: '光照',
  uv_index: '紫外线指数',
  rain_intensity: '雨强',
  rain_accum: '累计雨量',
  voltage: '电压',
  current: '电流',
  power: '功率',
  energy: '电量',
  soc: 'SOC',
  soh: 'SOH',
  frequency: '频率',
  // BMS sensors
  total_voltage: '总电压',
  rsoc: 'SOC',
  remaining_capacity: '剩余容量',
  protection_status: '保护状态',
  fet_status: 'MOS状态',
  temperature_1: '温度1',
  temperature_2: '温度2',
  temperature_3: '温度3',
  cell_voltage_max: '最高单体电压',
  cell_voltage_min: '最低单体电压',
  // Inverter - PV
  pv1_voltage: 'PV1电压',
  pv1_current: 'PV1电流',
  pv1_power: 'PV1功率',
  pv2_voltage: 'PV2电压',
  pv2_current: 'PV2电流',
  pv2_power: 'PV2功率',
  // Inverter - Grid
  grid_voltage: '电网电压',
  grid_frequency: '电网频率',
  // Inverter - Output
  output_voltage: '输出电压',
  output_frequency: '输出频率',
  output_apparent_power: '视在功率',
  output_active_power: '有功功率',
  output_load_percent: '负载百分比',
  // Inverter - Battery
  battery_voltage: '电池电压',
  battery_capacity: '电池容量',
  battery_charge_current: '充电电流',
  battery_discharge_current: '放电电流',
  bus_voltage: 'BUS电压',
  // Inverter - Temperature
  pv_temp: 'PV温度',
  inverter_temp: '逆变温度',
  boost_temp: '升压温度',
  transformer_temp: '变压器温度',
  max_temp: '最高温度',
  pv2_temp: 'PV2温度',
  dc_rectifier_temp: 'DC整流温度',
  // Inverter - Fan
  fan1_speed: '风扇1转速',
  fan2_speed: '风扇2转速',
  fan1_status: '风扇1状态',
  fan2_status: '风扇2状态',
  // Inverter - Energy
  daily_energy: '日发电量',
  monthly_energy: '月发电量',
  yearly_energy: '年发电量',
  total_energy: '总发电量',
  // Inverter - Status
  fault_code: '故障代码',
  work_mode: '工作模式',
  // Inverter - Alarms
  alarm_pv_to_load: 'PV馈能负载',
  alarm_output: '有输出',
  alarm_battery_low: '电池低电报警',
  alarm_battery_missing: '电池未接',
  alarm_overload: '输出过载',
  alarm_overtemp: '机器过温',
  alarm_eeprom_data: 'EEPROM数据异常',
  alarm_eeprom_rw: 'EEPROM读写异常',
  alarm_pv_low: 'PV功率过低',
  alarm_input_overvoltage: '输入电压过高',
  alarm_battery_overvoltage: '电池电压过高',
  alarm_fan_error: '风扇异常',
  // Inverter - BMS
  bms_comm_ok: 'BMS通信正常',
  bms_charge_allowed: 'BMS允许充电',
  bms_discharge_allowed: 'BMS允许放电',
  bms_soc: 'BMS当前SOC',
  bms_charge_current: 'BMS充电电流',
  bms_discharge_current: 'BMS放电电流',
  bms_charge_voltage_limit: 'BMS充电电压限制',
  bms_discharge_voltage_limit: 'BMS放电电压限制',
  bms_charge_current_limit: 'BMS充电电流限制',
  bms_temp: 'BMS平均温度',
}

/** 传感器单位映射 */
export const sensorUnitMap: Record<string, string> = {
  temperature: '°C',
  pressure: 'hPa',
  humidity: '%',
  wind_direction: '°',
  wind_speed: 'm/s',
  light: 'lux',
  noise: 'dB',
  co2: 'ppm',
  pm25: 'μg/m³',
  rainfall: 'mm',
  uv: 'μW/cm²',
  illuminance: 'lux',
  uv_index: '',
  rain_intensity: 'mm/h',
  rain_accum: 'mm',
  voltage: 'V',
  current: 'A',
  power: 'W',
  energy: 'kWh',
  soc: '%',
  soh: '%',
  frequency: 'Hz',
  // BMS sensors
  total_voltage: 'V',
  rsoc: '%',
  remaining_capacity: 'Ah',
  protection_status: '',
  fet_status: '',
  temperature_1: '°C',
  temperature_2: '°C',
  temperature_3: '°C',
  cell_voltage_max: 'V',
  cell_voltage_min: 'V',
  // Inverter - PV
  pv1_voltage: 'V',
  pv1_current: 'A',
  pv1_power: 'W',
  pv2_voltage: 'V',
  pv2_current: 'A',
  pv2_power: 'W',
  // Inverter - Grid
  grid_voltage: 'V',
  grid_frequency: 'Hz',
  // Inverter - Output
  output_voltage: 'V',
  output_frequency: 'Hz',
  output_apparent_power: 'VA',
  output_active_power: 'W',
  output_load_percent: '%',
  // Inverter - Battery
  battery_voltage: 'V',
  battery_capacity: '%',
  battery_charge_current: 'A',
  battery_discharge_current: 'A',
  bus_voltage: 'V',
  // Inverter - Temperature
  pv_temp: '°C',
  inverter_temp: '°C',
  boost_temp: '°C',
  transformer_temp: '°C',
  max_temp: '°C',
  pv2_temp: '°C',
  dc_rectifier_temp: '°C',
  // Inverter - Fan
  fan1_speed: '%',
  fan2_speed: '%',
  fan1_status: '',
  fan2_status: '',
  // Inverter - Energy
  daily_energy: 'kWh',
  monthly_energy: 'kWh',
  yearly_energy: 'kWh',
  total_energy: 'kWh',
  // Inverter - Status
  fault_code: '',
  work_mode: '',
  // Inverter - Alarms
  alarm_pv_to_load: '',
  alarm_output: '',
  alarm_battery_low: '',
  alarm_battery_missing: '',
  alarm_overload: '',
  alarm_overtemp: '',
  alarm_eeprom_data: '',
  alarm_eeprom_rw: '',
  alarm_pv_low: '',
  alarm_input_overvoltage: '',
  alarm_battery_overvoltage: '',
  alarm_fan_error: '',
  // Inverter - BMS
  bms_comm_ok: '',
  bms_charge_allowed: '',
  bms_discharge_allowed: '',
  bms_soc: '%',
  bms_charge_current: 'A',
  bms_discharge_current: 'A',
  bms_charge_voltage_limit: 'V',
  bms_discharge_voltage_limit: 'V',
  bms_charge_current_limit: 'A',
  bms_temp: '°C',
}

/** 预定义传感器类型排序（已知类型按此顺序排列，未知类型排后面） */
export const SENSOR_ORDER = [
  'temperature', 'humidity', 'pressure',
  'wind_direction', 'wind_speed',
  'light', 'noise',
  'co2', 'pm25', 'rainfall', 'uv',
]
