package models

import (
	"encoding/json"
	"time"
)

// CommandExecution is the durable business record for one device action.
// The command ID is generated by the server and is stable across outbox retry.
type CommandExecution struct {
	CommandID      string `gorm:"primaryKey;size:36" json:"command_id"`
	EdgeDeviceID   uint   `gorm:"not null;index" json:"edge_device_id"`
	NodeID         string `gorm:"size:32;not null;index;index:idx_command_execution_channel,priority:1" json:"node_id"`
	DeviceType     string `gorm:"size:32;not null" json:"device_type"`
	DeviceConfigID uint   `gorm:"not null" json:"device_config_id"`
	ChannelID      uint   `gorm:"not null;index:idx_command_execution_channel,priority:2" json:"channel_id"`
	ManifestID     string `gorm:"size:64;not null" json:"manifest_id"`
	ActionID       string `gorm:"size:96;not null" json:"action_id"`
	ActionVersion  int    `gorm:"not null" json:"action_version"`
	// CommandEngineRevision freezes the capability contract observed while the
	// action was admitted. A queued execution must not silently migrate onto a
	// later, incompatible firmware command engine.
	CommandEngineRevision uint32    `gorm:"not null;default:0" json:"command_engine_revision"`
	ActorUserID           uint      `gorm:"not null;index" json:"actor_user_id"`
	IdempotencyScope      string    `gorm:"size:160;not null;uniqueIndex:idx_command_idempotency" json:"-"`
	IdempotencyKey        string    `gorm:"size:128;not null;uniqueIndex:idx_command_idempotency" json:"-"`
	RequestHash           string    `gorm:"size:64;not null" json:"request_hash"`
	ParamsJSON            string    `gorm:"type:text;not null" json:"params_json"`
	Status                string    `gorm:"size:32;not null;index" json:"status"`
	DeadlineAt            time.Time `gorm:"not null;index" json:"deadline_at"`
	FinalReason           string    `gorm:"size:256" json:"final_reason,omitempty"`
	// VerifiedResultJSON is a server-produced, driver-parsed projection of a
	// successful Final.  Raw control bytes remain in the device protocol path
	// and are deliberately not exposed as a generic operation result.
	VerifiedResultJSON string                   `gorm:"type:jsonb;default:'[]'" json:"-"`
	CreatedAt          time.Time                `gorm:"not null;index" json:"created_at"`
	UpdatedAt          time.Time                `json:"updated_at"`
	CompletedAt        *time.Time               `gorm:"index" json:"completed_at,omitempty"`
	ManualResolution   *CommandManualResolution `gorm:"foreignKey:CommandID;references:CommandID" json:"manual_resolution,omitempty"`
}

func (c CommandExecution) MarshalJSON() ([]byte, error) {
	type alias CommandExecution
	verified := json.RawMessage(c.VerifiedResultJSON)
	if !json.Valid(verified) {
		verified = json.RawMessage("[]")
	}
	return json.Marshal(struct {
		alias
		VerifiedResult json.RawMessage `json:"verified_result"`
	}{alias: alias(c), VerifiedResult: verified})
}

// CommandManualResolution appends an operator conclusion to an UNKNOWN
// execution without rewriting the immutable physical outcome. CommandID is a
// primary key so concurrent or conflicting second resolutions fail closed.
type CommandManualResolution struct {
	CommandID  string    `gorm:"primaryKey;size:36" json:"-"`
	Outcome    string    `gorm:"size:32;not null;index" json:"outcome"`
	Reason     string    `gorm:"size:512;not null" json:"reason"`
	ResolvedBy uint      `gorm:"not null;index" json:"resolved_by"`
	ResolvedAt time.Time `gorm:"not null;index" json:"resolved_at"`
}

// CommandAttempt is a physical-delivery attempt. Phase 1 creates an attempt
// only when a dispatcher actually accepts an outbox record for transport.
type CommandAttempt struct {
	ID           uint64     `gorm:"primaryKey" json:"id"`
	CommandID    string     `gorm:"size:36;not null;uniqueIndex:idx_command_attempt" json:"command_id"`
	AttemptNo    uint32     `gorm:"not null;uniqueIndex:idx_command_attempt" json:"attempt_no"`
	Status       string     `gorm:"size:32;not null;index" json:"status"`
	EnvelopeID   string     `gorm:"size:64;not null;uniqueIndex" json:"envelope_id"`
	WireDigest   string     `gorm:"size:64;not null" json:"wire_digest"`
	BootID       string     `gorm:"size:96" json:"boot_id,omitempty"`
	FencingToken uint64     `gorm:"not null" json:"fencing_token"`
	CreatedAt    time.Time  `gorm:"not null;index" json:"created_at"`
	PublishedAt  *time.Time `json:"published_at,omitempty"`
	CompletedAt  *time.Time `json:"completed_at,omitempty"`
}

// CommandOutbox is the transactional publication record. A nil ProcessedAt
// means it has not been handed to the transport; a lease prevents two workers
// from dispatching it concurrently.
type CommandOutbox struct {
	ID             uint64     `gorm:"primaryKey" json:"id"`
	CommandID      string     `gorm:"size:36;not null;uniqueIndex" json:"command_id"`
	EventType      string     `gorm:"size:64;not null" json:"event_type"`
	PayloadJSON    string     `gorm:"type:text;not null" json:"-"`
	State          string     `gorm:"size:24;not null;index" json:"state"`
	LeaseOwner     string     `gorm:"size:96;index" json:"lease_owner,omitempty"`
	LeaseExpiresAt *time.Time `gorm:"index" json:"lease_expires_at,omitempty"`
	FencingToken   uint64     `gorm:"not null;default:0" json:"fencing_token"`
	ProcessedAt    *time.Time `gorm:"index" json:"processed_at,omitempty"`
	CreatedAt      time.Time  `gorm:"not null;index" json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

// CommandInbox records every received command event before it drives the
// state machine. EventID is globally unique, so duplicate delivery is inert.
type CommandInbox struct {
	EventID     string    `gorm:"primaryKey;size:96" json:"event_id"`
	CommandID   string    `gorm:"size:36;not null;index" json:"command_id"`
	EventType   string    `gorm:"size:48;not null" json:"event_type"`
	AttemptNo   uint32    `gorm:"not null" json:"attempt_no"`
	BootID      string    `gorm:"size:96" json:"boot_id,omitempty"`
	PayloadJSON string    `gorm:"type:text;not null" json:"-"`
	ReceivedAt  time.Time `gorm:"not null;index" json:"received_at"`
}
